name: Documentation
on:
  # workflow_run:
  #   workflows: ['Testing']
  #   types: [completed]
  #   branches: ["cx", "main"]
  workflow_call:
    inputs:
      test-run-id:
        required: true
        type: string
    
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --with docs
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Setting up Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .ci-cache
          restore-keys: |
            mkdocs-material-
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          run-id: ${{ inputs.test-run-id }}
          path: docs/coverage/
      - name: Deploy
        run: poetry run mkdocs gh-deploy --force